server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
          filters:
            - PrefixPath=/api/v1
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/users/**
          filters:
            - PrefixPath=/api/v1