server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/auth/**
          filters:
            - PrefixPath=/api/v1
        - id: user-service
          uri: ${USER_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/users/**
          filters:
            - PrefixPath=/api/v1
        - id: product-catalog
          uri: ${PRODUCT_CATALOG_URL:http://localhost:8083}
          predicates:
            - Path=/products/**, /categories/**
          filters:
            - PrefixPath=/api/v1
        - id: cart-service
          uri: ${CART_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/cart, /cart/**
          filters:
            - PrefixPath=/api/v1
        - id: order-service
          uri: ${ORDER_SERVICE_URL:http://localhost:8085}
          predicates:
            - Path=/orders, /orders/**
          filters:
            - PrefixPath=/api/v1