server:
  port: 8088

spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    from: noreply@shopnow.com
    properties:
      mail.smtp.auth: ${MAIL_SMTP_AUTH:false}
      mail.smtp.starttls.enable: ${MAIL_SMTP_STARTTLS:false}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}

auth-service:
  base-url: ${AUTH_SERVICE_URL:http://localhost:8081}
