version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: auth-service-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: auth-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
